### ISSUE TITLE
Release for moving the ADMM part to `ExaAdmm.jl`

### ISSUE THREAD

**Issue by kibaekkim** [exanauts/ExaTron.jl#32]
A major version update (v0.2.0) based on branch `youngdae/multiperiod` will be released to completely move the ADMM part to `ExaAdmm.jl`, which will be release as a separate package (https://github.com/exanauts/ExaAdmm.jl/issues/3).

TODOs:

- [x] #33

**Comment by michel2323** [comment]
@JuliaRegistrator register
