### ISSUE TITLE
Solution difference in 1e-5 from dtron on CPU vs. GPU

### ISSUE THREAD

**Issue by kibaekkim** [exanauts/ExaTron.jl#52]
`dtron` can generate different solutions from running on CPU and CUDA. The difference is in 1e-5.

**Comment by kibaekkim** [comment]
I am adding @michel2323 for the KA part, which I did not test yet.

**Comment by kibaekkim** [comment]
I further narrowed down to a particular function that returns different solutions: `dspcg` I added more tests related to that: https://github.com/exanauts/ExaTron.jl/commit/d3f8d191495f530fbe390a9241004f2194256d99

**Comment by youngdae** [comment]
I've noticed that matrix A is not given as a symmetric matrix. ExaTron assumes that a symmetric matrix is given. Could you try with a symmetric matrix?

**Comment by wzhangw** [comment]
Resolved now. Code is modified on the ExaAdmm side to ensure GPU provides symmetric matrix evaluation for Hessian. CPU doesn't have to, only lower triangular entries are fine.

**Comment by kibaekkim** [comment]
@wzhangw and I concluded that this is not the issue of `ExaTron.jl`. Thanks @youngdae for the help.
